services:
  # Web Service para Django + React
  - type: web
    name: hoja-de-vida-carmen
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
<<<<<<< HEAD
=======
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: SEED_DATA
        value: True
>>>>>>> d07955a532472cc349855f08a265beab260c6dd7
      - key: DATABASE_URL
        fromDatabase:
          name: hoja-de-vida-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: hoja-de-vida-db
    plan: free
    databaseName: hoja_de_vida_db
    user: hoja_de_vida_user
